import './globals.css'
import localFont from 'next/font/local'

const sarabun = localFont({
  src: [
    {
      path: '../fonts/Sarabun-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../fonts/Sarabun-ThinItalic.ttf',
      weight: '100',
      style: 'italic',
    },
    {
      path: '../fonts/Sarabun-ExtraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../fonts/Sarabun-ExtraLightItalic.ttf',
      weight: '200',
      style: 'italic',
    },
    {
      path: '../fonts/Sarabun-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/Sarabun-LightItalic.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../fonts/Sarabun-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/Sarabun-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../fonts/Sarabun-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/Sarabun-MediumItalic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../fonts/Sarabun-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../fonts/Sarabun-SemiBoldItalic.ttf',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../fonts/Sarabun-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/Sarabun-BoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../fonts/Sarabun-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../fonts/Sarabun-ExtraBoldItalic.ttf',
      weight: '800',
      style: 'italic',
    },
  ],
  variable: '--font-sarabun',
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th">
      <body className={`${sarabun.className} ${sarabun.variable}`}>
        {children}
      </body>
    </html>
  )
}




/////////////////////////////////////////////////
// --------- the old one
/////////////////////////////////////////////////

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Checkpd Records",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
